name: Generate snake animation

on:
  schedule:
    # executa 2x por dia (00:00 e 12:00 UTC)
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write     # permite o push no branch 'output'

    steps:
      # 1) clona o repositório
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2) gera a(s) SVG(s)
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: thavyne-KDR
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      # 3) faz commit e push no branch 'output'
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output      # cria/atualiza esse branch
          build_dir: dist            # pasta com os SVGs
          commit_message: "chore: update snake animation"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
